[package]
name = "diesel_demo_step_2_pg"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
diesel = { version = "2.1.0", path = "../../../diesel", features = ["postgres"] }
dotenvy = "0.15"

[dev-dependencies]
assert_cmd = "2.0.14"

[[bin]]
name = "show_posts"
doc = false

[[bin]]
name = "write_post"
doc = false

[lib]
doc = false
